---
# tasks file for install_docker

- name: Configuring Docker Repository
  yum_repository:
    name: docker
    description: docker yum repository
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
    gpgcheck: no

- name: Installing Docker
  package:
      name: docker-ce-3:18.09.1-3.el7
      state: present

- name: Installing Python 3
  package:
    name: python36
    state: present

- pip:
    name: docker-py

- name: Starting Docker Services
  service:
    name: docker
    state: started
    enabled: yes
